### ISSUE TITLE
playlist_generate examples

### ISSUE THREAD

**Issue by paulijar** [ampache/python3-ampache#6]
I was wondering, how the response for the API method `playlist_generate` should look like when the `format` is `id` or `index`. There are three examples:
https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/playlist_generate%20(id).xml
https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/playlist_generate%20(index).xml
https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/playlist_generate%20(song).xml

...but those all seem to contain a list of `song` elements. Is there something I don't realize, or are the examples for the `id` and `index` format totally wrong?

**Comment by lachlan-00** [comment]
it's actually a bug that i just fixed.

The format parameter was being overwritten by the json/xml api 'format' i'll need to update those docs now that it's fixed. Thanks!

**Comment by lachlan-00** [comment]
updated the examples.

Thanks for reporting! it needed a bit more work to make it valid XML.

**Comment by paulijar** [comment]
Okay, great. Did you notice, that the same issue is still in the corresponding JSON examples?

**Comment by lachlan-00** [comment]
No I didn't! Will fix that up too

**Comment by lachlan-00** [comment]
updated json too.

I'm going to be doing a runover again before i release the new api site and ampache 4.2.2
